version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 3000

  server:
    image: clusterzx/paperless-ai:v2.6.4
    user: "1000:1000"
    init: true
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: "1000"
      PGID: "1000"
      PAPERLESS_AI_PORT: "3000"
      RAG_SERVICE_URL: "http://localhost:8000"
      RAG_SERVICE_ENABLED: "false"
    volumes:
      - ${APP_DATA_DIR}:/app/data
